const pokemons = [
  {
    num: 1,
    name: "Bulbasaur",
    url: "./pokemon/bulbasaur.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 2,
    name: "Ivysaur",
    url: "./pokemon/ivysaur.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 3,
    name: "Venusaur",
    url: "./pokemon/ivysaur.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 4,
    name: "Charmander",
    url: "./pokemon/charmander.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 5,
    name: "Charmeleon",
    url: "./pokemon/charmeleon.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 6,
    name: "Charizard",
    url: "./pokemon/charizard.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 7,
    name: "Squirtle",
    url: "./pokemon/squirtle.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 8,
    name: "Wartortle",
    url: "./pokemon/wartortle.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 9,
    name: "Blastoise",
    url: "./pokemon/blastoise.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 10,
    name: "Caterpie",
    url: "./pokemon/caterpie.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 11,
    name: "Metapod",
    url: "./pokemon/metapod.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 12,
    name: "Butterfree",
    url: "./pokemon/butterfree.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 13,
    name: "Weedle",
    url: "./pokemon/weedle.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 14,
    name: "Kakuna",
    url: "./pokemon/kakuna.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 15,
    name: "Beedrill",
    url: "./pokemon/beedrill.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 16,
    name: "Pidgey",
    url: "./pokemon/pidgey.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 17,
    name: "Pidgeotto",
    url: "./pokemon/pidgeotto.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  {
    num: 18,
    name: "Pidgeot",
    url: "./pokemon/pidgeot.png",
    catched: false,
    isDisplayed: false,
    isSelected: false,
  },
  // {
  //   num: 19,
  //   name: "Rattata",
  //   url: "./pokemon/rattata.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 20,
  //   name: "Raticate",
  //   url: "./pokemon/raticate.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 21,
  //   name: "Spearow",
  //   url: "./pokemon/spearow.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 22,
  //   name: "Fearow",
  //   url: "./pokemon/fearow.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 23,
  //   name: "Ekans",
  //   url: "./pokemon/ekans.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 24,
  //   name: "Arbok",
  //   url: "./pokemon/arbok.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 25,
  //   name: "Pikachu",
  //   url: "./pokemon/pikachu.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 26,
  //   name: "Raichu",
  //   url: "./pokemon/raichu.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 27,
  //   name: "Sandshrew",
  //   url: "./pokemon/sandshrew.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 28,
  //   name: "Sandslash",
  //   url: "./pokemon/sandslash.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: "29 & 32",
  //   name: "Nidoran",
  //   url: "./pokemon/nidoran.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 30,
  //   name: "Nidorina",
  //   url: "./pokemon/nidorina.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 31,
  //   name: "Nidoqueen",
  //   url: "./pokemon/nidoqueen.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 33,
  //   name: "Nidorino",
  //   url: "./pokemon/nidorino.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 34,
  //   name: "Nidoking",
  //   url: "./pokemon/nidoking.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 35,
  //   name: "Clefairy",
  //   url: "./pokemon/clefairy.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 36,
  //   name: "Clefable",
  //   url: "./pokemon/clefable.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 37,
  //   name: "Vulpix",
  //   url: "./pokemon/vulpix.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 38,
  //   name: "Ninetales",
  //   url: "./pokemon/ninetales.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 39,
  //   name: "Jigglypuff",
  //   url: "./pokemon/jigglypuff.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 40,
  //   name: "Wigglytuff",
  //   url: "./pokemon/wigglytuff.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 41,
  //   name: "Zubat",
  //   url: "./pokemon/zubat.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 42,
  //   name: "Golbat",
  //   url: "./pokemon/golbat.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 43,
  //   name: "Oddish",
  //   url: "./pokemon/oddish.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 44,
  //   name: "Gloom",
  //   url: "./pokemon/gloom.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 45,
  //   name: "Vileplume",
  //   url: "./pokemon/vileplume.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 46,
  //   name: "Paras",
  //   url: "./pokemon/paras.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 47,
  //   name: "Parasect",
  //   url: "./pokemon/parasect.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 48,
  //   name: "Venonat",
  //   url: "./pokemon/venonat.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 49,
  //   name: "Venomoth",
  //   url: "./pokemon/venomoth.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
  // {
  //   num: 50,
  //   name: "Diglett",
  //   url: "./pokemon/diglett.png",
  //   catched: false,
  //   isDisplayed: false,
  //   isSelected: false,
  // },
];

export default pokemons;
